---
version: '3.8'
services:

  terraform-utils:
    image: python:3.9.16
    working_dir: /infra/infrastructure
    entrypoint: [""]
    volumes:
      - ~/.aws:/root/.aws:ro
      - .:/infra:rw
    environment:
      - AWS_REGION
      - AWS_DEFAULT_REGION
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_PROFILE
  
  checkov:
    image: bridgecrew/checkov:${CHECKOV_VERSION:-2}
    working_dir: /infrastructure
    volumes:
      - .:/infrastructure:rw
      - ~/.ssh:/root/.ssh
    environment:
      - AWS_DEFAULT_REGION
      - AWS_SECRET_ACCESS_KEY
      - AWS_ACCESS_KEY_ID
      - AWS_SESSION_TOKEN

  nodejs:
    image: node:18-alpine
    working_dir: /opt/app/react-app
    volumes:      
      - .:/opt/app:rw
    